# Site settings
title: Ben McCary
description: 'A site about me, a wonderful guy.'
url: 'http://benmccary.github.io'
baseurl: '/'


author:
  name: 'Ben MCCary'
  email: benjamin.mccary@gmail.com
  twitter_username: 
  facebook_username: ben.mccary9
  github_username:  benmccary
  linkedin_username:  ben-mccary-47651189

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
